from pathlib import Path
import sys

import pytest
from pydantic import ValidationError

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from dpdl.configurationmanager import Configuration


@pytest.mark.parametrize(
    ("kwargs", "is_valid", "error_match"),
    [
        (
            {
                "command": "train",
                "noise_mechanism": "gaussian",
                "accountant": "prv",
            },
            True,
            None,
        ),
        (
            {
                "command": "train",
                "noise_mechanism": "gaussian",
                "accountant": "bsr",
            },
            False,
            "Gaussian mechanism does not support mechanism-specific accountants",
        ),
        (
            {
                "command": "train",
                "noise_mechanism": "bsr",
                "accountant": "bsr",
                "poisson_sampling": False,
                "bsr_coeffs": [1.0, 0.2],
            },
            True,
            None,
        ),
        (
            {
                "command": "train",
                "noise_mechanism": "bsr",
                "accountant": "prv",
                "poisson_sampling": False,
                "bsr_coeffs": [1.0],
            },
            False,
            "requires --accountant bsr",
        ),
        (
            {
                "command": "train",
                "noise_mechanism": "bnb",
                "accountant": "bnb",
                "poisson_sampling": False,
                "sampling_mode": "b_min_sep",
                "bnb_b": 2,
                "bnb_p": 0.2,
                "bnb_bands": 2,
            },
            True,
            None,
        ),
        (
            {
                "command": "train",
                "noise_mechanism": "bnb",
                "accountant": "bnb",
                "poisson_sampling": False,
                "sampling_mode": "balls_in_bins",
                "bnb_b": 4,
                "bnb_bands": 2,
            },
            True,
            None,
        ),
        (
            {
                "command": "train",
                "noise_mechanism": "bnb",
                "accountant": "bnb",
                "poisson_sampling": True,
                "sampling_mode": "b_min_sep",
                "bnb_b": 2,
                "bnb_p": 0.2,
                "bnb_bands": 2,
            },
            False,
            "BNB mechanism requires non-Poisson semantics",
        ),
        (
            {
                "command": "train",
                "noise_mechanism": "bnb",
                "accountant": "bnb",
                "poisson_sampling": False,
                "sampling_mode": "torch_sampler",
                "bnb_b": 2,
                "bnb_p": 0.2,
                "bnb_bands": 2,
            },
            False,
            "requires --sampling-mode b_min_sep or balls_in_bins",
        ),
        (
            {
                "command": "train",
                "noise_mechanism": "gaussian",
                "sampling_mode": "b_min_sep",
            },
            False,
            "BNB-specific sampling requires --noise-mechanism bnb",
        ),
    ],
)
def test_dp_contract_table_for_legal_and_illegal_mode_combinations(
    kwargs: dict,
    is_valid: bool,
    error_match: str | None,
) -> None:
    if is_valid:
        cfg = Configuration(**kwargs)
        assert cfg.command == "train"
        return

    with pytest.raises(ValidationError, match=error_match):
        Configuration(**kwargs)


def test_bsr_configuration_valid_minimal() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bsr',
        accountant='bsr',
        poisson_sampling=False,
        bsr_coeffs=[1.0, 0.2],
    )
    assert cfg.noise_mechanism == 'bsr'
    assert cfg.accountant == 'bsr'
    assert cfg.bsr_coeffs == [1.0, 0.2]


def test_bsr_configuration_valid_autogenerated_coeffs() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bsr',
        accountant='bsr',
        poisson_sampling=False,
        bsr_bands=5,
    )
    assert cfg.noise_mechanism == 'bsr'
    assert cfg.bsr_bands == 5


def test_bsr_configuration_rejects_poisson_sampling() -> None:
    with pytest.raises(ValidationError, match='non-Poisson semantics'):
        Configuration(
            command='train',
            noise_mechanism='bsr',
            accountant='bsr',
            poisson_sampling=True,
            bsr_coeffs=[1.0],
        )


def test_bsr_configuration_requires_bands_for_cyclic_poisson() -> None:
    with pytest.raises(ValidationError, match='requires --bsr-bands'):
        Configuration(
            command='train',
            noise_mechanism='bsr',
            accountant='bsr',
            poisson_sampling=False,
            sampling_mode='cyclic_poisson',
            bsr_coeffs=[1.0],
        )


def test_bsr_configuration_allows_torch_sampler_literal() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bsr',
        accountant='bsr',
        poisson_sampling=False,
        sampling_mode='torch_sampler',
        bsr_coeffs=[1.0],
    )
    assert cfg.sampling_mode == 'torch_sampler'


@pytest.mark.parametrize(
    ("overrides", "error_match"),
    [
        (
            {
                'accountant': 'prv',
            },
            'requires --accountant bsr',
        ),
        (
            {
                'poisson_sampling': True,
            },
            'requires non-Poisson semantics',
        ),
        (
            {
                'sampling_mode': 'cyclic_poisson',
                'bsr_coeffs': [1.0],
                'bsr_bands': None,
            },
            'requires --bsr-bands',
        ),
        (
            {
                'sampling_mode': 'b_min_sep',
            },
            'BNB-specific sampling requires --noise-mechanism bnb',
        ),
        (
            {
                'sampling_mode': 'balls_in_bins',
            },
            'BNB-specific sampling requires --noise-mechanism bnb',
        ),
        (
            {
                'sampling_mode': 'cyclic_poisson',
                'bsr_bands': 3,
                'bsr_mf_sensitivity': 1.0,
            },
            'fixed-batch BSR only',
        ),
    ],
)
def test_bsr_invalid_combo_matrix(overrides: dict, error_match: str) -> None:
    params = {
        'command': 'train',
        'noise_mechanism': 'bsr',
        'accountant': 'bsr',
        'poisson_sampling': False,
        'sampling_mode': 'torch_sampler',
        'bsr_coeffs': [1.0],
    }
    params.update(overrides)

    with pytest.raises(ValidationError, match=error_match):
        Configuration(**params)


@pytest.mark.parametrize(
    ("overrides", "error_match"),
    [
        (
            {
                'noise_mechanism': 'gaussian',
                'accountant': 'rdp',
                'bsr_coeffs': None,
                'bsr_iterations_number': 10,
            },
            'BSR-specific parameters require --noise-mechanism bsr',
        ),
        (
            {
                'bsr_iterations_number': 0,
            },
            'bsr-iterations-number',
        ),
        (
            {
                'use_steps': True,
                'total_steps': 10,
                'sampling_mode': None,
            },
            'requires --sampling-mode',
        ),
        (
            {
                'use_steps': True,
                'total_steps': 10,
                'sampling_mode': 'cyclic_poisson',
                'bsr_bands': 3,
                'bsr_iterations_number': 0,
            },
            'bsr-iterations-number',
        ),
    ],
)
def test_bsr_horizon_invalid_combo_matrix(overrides: dict, error_match: str) -> None:
    params = {
        'command': 'train',
        'noise_mechanism': 'bsr',
        'accountant': 'bsr',
        'poisson_sampling': False,
        'sampling_mode': 'torch_sampler',
        'bsr_coeffs': [1.0],
    }
    params.update(overrides)

    with pytest.raises(ValidationError, match=error_match):
        Configuration(**params)


@pytest.mark.parametrize(
    ("field", "value", "error_match"),
    [
        ("bsr_mf_sensitivity", 1.0, "fixed-batch BSR only"),
        ("bsr_max_participations", 10, "fixed-batch BSR only"),
        ("bsr_min_separation", 5, "fixed-batch BSR only"),
    ],
)
def test_bsr_cyclic_poisson_rejects_fixed_batch_only_knobs(field, value, error_match) -> None:
    kwargs = {
        'command': 'train',
        'noise_mechanism': 'bsr',
        'accountant': 'bsr',
        'poisson_sampling': False,
        'sampling_mode': 'cyclic_poisson',
        'bsr_bands': 3,
        field: value,
    }
    with pytest.raises(ValidationError, match=error_match):
        Configuration(**kwargs)


def test_cyclic_poisson_requires_bsr_mechanism() -> None:
    with pytest.raises(ValidationError, match='requires --noise-mechanism bsr'):
        Configuration(
            command='train',
            noise_mechanism='gaussian',
            sampling_mode='cyclic_poisson',
        )


def test_removed_bsr_example_sgd_optimizer() -> None:
    with pytest.raises(ValidationError, match='bsr-example-sgd'):
        Configuration(
            command='train',
            optimizer='bsr-example-sgd',
            noise_mechanism='gaussian',
            accountant='rdp',
        )


def test_non_bsr_allows_empty_bsr_coeff_list_default() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='gaussian',
        accountant='rdp',
        bsr_coeffs=[],
    )
    assert cfg.noise_mechanism == 'gaussian'


def test_bsr_iterations_number_validation() -> None:
    with pytest.raises(ValidationError, match='bsr-iterations-number'):
        Configuration(
            command='train',
            noise_mechanism='bsr',
            accountant='bsr',
            poisson_sampling=False,
            bsr_bands=5,
            bsr_iterations_number=0,
        )


def test_bnb_configuration_valid_minimal() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bnb',
        accountant='bnb',
        poisson_sampling=False,
        sampling_mode='b_min_sep',
        bnb_b=2,
        bnb_p=0.1,
        bnb_bands=4,
    )
    assert cfg.noise_mechanism == 'bnb'
    assert cfg.sampling_mode == 'b_min_sep'
    assert cfg.bnb_b == 2
    assert cfg.bnb_p == 0.1
    assert cfg.bnb_bands == 4


def test_bnb_configuration_accepts_balls_in_bins_alias() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bnb',
        accountant='bnb',
        poisson_sampling=False,
        sampling_mode='balls_n_bins',
        bnb_b=2,
        bnb_p=0.1,
        bnb_bands=4,
    )
    assert cfg.sampling_mode == 'balls_in_bins'


def test_gaussian_rejects_mechanism_specific_accountants() -> None:
    with pytest.raises(ValidationError, match='Gaussian mechanism does not support mechanism-specific accountants'):
        Configuration(
            command='train',
            noise_mechanism='gaussian',
            accountant='bnb',
        )


def test_total_steps_nonpoisson_requires_explicit_custom_sampling_mode() -> None:
    with pytest.raises(ValidationError, match='requires --sampling-mode'):
        Configuration(
            command='train',
            use_steps=True,
            total_steps=10,
            poisson_sampling=False,
            noise_mechanism='gaussian',
            accountant='rdp',
        )


def test_total_steps_nonpoisson_accepts_explicit_custom_sampling_mode() -> None:
    cfg = Configuration(
        command='train',
        use_steps=True,
        total_steps=10,
        poisson_sampling=False,
        sampling_mode='cyclic_poisson',
        noise_mechanism='bsr',
        accountant='bsr',
        bsr_bands=3,
    )
    assert cfg.sampling_mode == 'cyclic_poisson'


def test_total_steps_nonpoisson_allows_bsr_torch_sampler_fixed_batch() -> None:
    cfg = Configuration(
        command='train',
        use_steps=True,
        total_steps=10,
        poisson_sampling=False,
        sampling_mode='torch_sampler',
        noise_mechanism='bsr',
        accountant='bsr',
        bsr_coeffs=[1.0],
    )
    assert cfg.sampling_mode == 'torch_sampler'


def test_total_steps_nonpoisson_bnb_torch_sampler_keeps_bnb_specific_error() -> None:
    with pytest.raises(ValidationError, match='requires --sampling-mode b_min_sep or balls_in_bins'):
        Configuration(
            command='train',
            use_steps=True,
            total_steps=10,
            poisson_sampling=False,
            sampling_mode='torch_sampler',
            noise_mechanism='bnb',
            accountant='bnb',
            bnb_b=2,
            bnb_p=0.1,
            bnb_bands=4,
        )


def test_bnb_configuration_allows_shared_bsr_coeffs_field() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bnb',
        accountant='bnb',
        poisson_sampling=False,
        sampling_mode='b_min_sep',
        bsr_coeffs=[1.0, 0.2],
        bnb_b=2,
        bnb_p=0.1,
        bnb_bands=4,
    )
    assert cfg.noise_mechanism == 'bnb'
    assert cfg.bsr_coeffs == [1.0, 0.2]


def test_bnb_configuration_rejects_poisson_sampling() -> None:
    with pytest.raises(ValidationError, match='non-Poisson semantics'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=True,
            sampling_mode='b_min_sep',
            bnb_b=2,
            bnb_p=0.1,
            bnb_bands=4,
        )


def test_b_min_sep_requires_bnb_mechanism() -> None:
    with pytest.raises(ValidationError, match='BNB-specific sampling requires --noise-mechanism bnb'):
        Configuration(
            command='train',
            noise_mechanism='gaussian',
            sampling_mode='b_min_sep',
        )


def test_bnb_configuration_requires_sampling_mode_b_min_sep() -> None:
    with pytest.raises(ValidationError, match='requires --sampling-mode b_min_sep or balls_in_bins'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='torch_sampler',
            bnb_b=2,
            bnb_p=0.1,
            bnb_bands=4,
        )


def test_balls_in_bins_requires_bnb_mechanism() -> None:
    with pytest.raises(ValidationError, match='BNB-specific sampling requires --noise-mechanism bnb'):
        Configuration(
            command='train',
            noise_mechanism='gaussian',
            sampling_mode='balls_in_bins',
        )


def test_bnb_configuration_balls_in_bins_does_not_require_p() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bnb',
        accountant='bnb',
        poisson_sampling=False,
        sampling_mode='balls_in_bins',
        bnb_b=10,
        bnb_bands=4,
    )
    assert cfg.sampling_mode == 'balls_in_bins'

def test_bnb_configuration_accepts_calibration_options() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bnb',
        accountant='bnb',
        poisson_sampling=False,
        sampling_mode='b_min_sep',
        bnb_b=2,
        bnb_p=0.2,
        bnb_bands=1,
        bnb_num_samples=500,
        bnb_seed=7,
    )
    assert cfg.bnb_num_samples == 500
    assert cfg.bnb_seed == 7


def test_bnb_configuration_rejects_invalid_calibration_options() -> None:
    with pytest.raises(ValidationError, match='--bnb-num-samples must be >= 1'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_b=2,
            bnb_p=0.2,
            bnb_bands=1,
            bnb_num_samples=0,
        )

def test_bnb_configuration_requires_all_b_min_sep_params() -> None:
    with pytest.raises(ValidationError, match='requires --bnb-b'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_p=0.1,
            bnb_bands=4,
        )

    with pytest.raises(ValidationError, match='requires --bnb-p'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_b=2,
            bnb_bands=4,
        )

    with pytest.raises(ValidationError, match='requires --bnb-bands'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_b=2,
            bnb_p=0.1,
        )


def test_bnb_configuration_rejects_invalid_param_ranges() -> None:
    with pytest.raises(ValidationError, match='--bnb-b must be >= 1'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_b=0,
            bnb_p=0.1,
            bnb_bands=4,
        )

    with pytest.raises(ValidationError, match='--bnb-p must be in \\(0, 1\\]'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_b=2,
            bnb_p=0.0,
            bnb_bands=4,
        )

    with pytest.raises(ValidationError, match='--bnb-bands must be >= 1'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_b=2,
            bnb_p=0.1,
            bnb_bands=0,
        )
