from pathlib import Path
import sys

import pytest
from pydantic import ValidationError

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from dpdl.configurationmanager import Configuration


def test_bsr_configuration_valid_minimal() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bsr',
        accountant='bsr',
        poisson_sampling=False,
        bsr_coeffs=[1.0, 0.2],
    )
    assert cfg.noise_mechanism == 'bsr'
    assert cfg.accountant == 'bsr'
    assert cfg.bsr_coeffs == [1.0, 0.2]


def test_bsr_configuration_valid_autogenerated_coeffs() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bsr',
        accountant='bsr',
        poisson_sampling=False,
        bsr_bands=5,
    )
    assert cfg.noise_mechanism == 'bsr'
    assert cfg.bsr_bands == 5


def test_bsr_configuration_rejects_poisson_sampling() -> None:
    with pytest.raises(ValidationError, match='fixed-batch semantics'):
        Configuration(
            command='train',
            noise_mechanism='bsr',
            accountant='bsr',
            poisson_sampling=True,
            bsr_coeffs=[1.0],
        )


def test_bsr_configuration_requires_bands_for_cyclic_poisson() -> None:
    with pytest.raises(ValidationError, match='requires --bsr-bands'):
        Configuration(
            command='train',
            noise_mechanism='bsr',
            accountant='bsr',
            poisson_sampling=False,
            sampling_mode='cyclic_poisson',
            bsr_coeffs=[1.0],
        )


def test_cyclic_poisson_requires_bsr_mechanism() -> None:
    with pytest.raises(ValidationError, match='requires --noise-mechanism bsr'):
        Configuration(
            command='train',
            noise_mechanism='gaussian',
            sampling_mode='cyclic_poisson',
        )


def test_bsr_alpha_beta_validation() -> None:
    with pytest.raises(ValidationError, match='bsr-alpha'):
        Configuration(
            command='train',
            noise_mechanism='bsr',
            accountant='bsr',
            poisson_sampling=False,
            bsr_bands=5,
            bsr_alpha=1.2,
        )

    with pytest.raises(ValidationError, match='bsr-beta'):
        Configuration(
            command='train',
            noise_mechanism='bsr',
            accountant='bsr',
            poisson_sampling=False,
            bsr_bands=5,
            bsr_beta=1.0,
        )


def test_non_bsr_allows_empty_bsr_coeff_list_default() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='gaussian',
        accountant='rdp',
        bsr_coeffs=[],
    )
    assert cfg.noise_mechanism == 'gaussian'
