from pathlib import Path
import sys

import pytest
from pydantic import ValidationError

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from dpdl.configurationmanager import Configuration


def test_bsr_configuration_valid_minimal() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bsr',
        accountant='bsr',
        poisson_sampling=False,
        bsr_coeffs=[1.0, 0.2],
    )
    assert cfg.noise_mechanism == 'bsr'
    assert cfg.accountant == 'bsr'
    assert cfg.bsr_coeffs == [1.0, 0.2]


def test_bsr_configuration_valid_autogenerated_coeffs() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bsr',
        accountant='bsr',
        poisson_sampling=False,
        bsr_bands=5,
    )
    assert cfg.noise_mechanism == 'bsr'
    assert cfg.bsr_bands == 5


def test_bsr_configuration_rejects_poisson_sampling() -> None:
    with pytest.raises(ValidationError, match='non-Poisson semantics'):
        Configuration(
            command='train',
            noise_mechanism='bsr',
            accountant='bsr',
            poisson_sampling=True,
            bsr_coeffs=[1.0],
        )


def test_bsr_configuration_requires_bands_for_cyclic_poisson() -> None:
    with pytest.raises(ValidationError, match='requires --bsr-bands'):
        Configuration(
            command='train',
            noise_mechanism='bsr',
            accountant='bsr',
            poisson_sampling=False,
            sampling_mode='cyclic_poisson',
            bsr_coeffs=[1.0],
        )


def test_bsr_configuration_allows_torch_sampler_literal() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bsr',
        accountant='bsr',
        poisson_sampling=False,
        sampling_mode='torch_sampler',
        bsr_coeffs=[1.0],
    )
    assert cfg.sampling_mode == 'torch_sampler'


def test_cyclic_poisson_requires_bsr_mechanism() -> None:
    with pytest.raises(ValidationError, match='requires --noise-mechanism bsr'):
        Configuration(
            command='train',
            noise_mechanism='gaussian',
            sampling_mode='cyclic_poisson',
        )


def test_bsr_alpha_beta_validation() -> None:
    with pytest.raises(ValidationError, match='bsr-alpha'):
        Configuration(
            command='train',
            noise_mechanism='bsr',
            accountant='bsr',
            poisson_sampling=False,
            bsr_bands=5,
            bsr_alpha=1.2,
        )

    with pytest.raises(ValidationError, match='bsr-beta'):
        Configuration(
            command='train',
            noise_mechanism='bsr',
            accountant='bsr',
            poisson_sampling=False,
            bsr_bands=5,
            bsr_beta=1.0,
        )


def test_non_bsr_allows_empty_bsr_coeff_list_default() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='gaussian',
        accountant='rdp',
        bsr_coeffs=[],
    )
    assert cfg.noise_mechanism == 'gaussian'


def test_bsr_iterations_number_validation() -> None:
    with pytest.raises(ValidationError, match='bsr-iterations-number'):
        Configuration(
            command='train',
            noise_mechanism='bsr',
            accountant='bsr',
            poisson_sampling=False,
            bsr_bands=5,
            bsr_iterations_number=0,
        )


def test_bnb_configuration_valid_minimal() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bnb',
        accountant='bnb',
        poisson_sampling=False,
        sampling_mode='b_min_sep',
        bnb_b=2,
        bnb_p=0.1,
        bnb_bands=4,
    )
    assert cfg.noise_mechanism == 'bnb'
    assert cfg.sampling_mode == 'b_min_sep'
    assert cfg.bnb_b == 2
    assert cfg.bnb_p == 0.1
    assert cfg.bnb_bands == 4


def test_bnb_configuration_accepts_balls_in_bins_alias() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bnb',
        accountant='bnb',
        poisson_sampling=False,
        sampling_mode='balls_n_bins',
        bnb_b=2,
        bnb_p=0.1,
        bnb_bands=4,
    )
    assert cfg.sampling_mode == 'balls_in_bins'


def test_bnb_configuration_allows_shared_bsr_coeffs_field() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bnb',
        accountant='bnb',
        poisson_sampling=False,
        sampling_mode='b_min_sep',
        bsr_coeffs=[1.0, 0.2],
        bnb_b=2,
        bnb_p=0.1,
        bnb_bands=4,
    )
    assert cfg.noise_mechanism == 'bnb'
    assert cfg.bsr_coeffs == [1.0, 0.2]


def test_bnb_configuration_rejects_poisson_sampling() -> None:
    with pytest.raises(ValidationError, match='non-Poisson semantics'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=True,
            sampling_mode='b_min_sep',
            bnb_b=2,
            bnb_p=0.1,
            bnb_bands=4,
        )


def test_b_min_sep_requires_bnb_mechanism() -> None:
    with pytest.raises(ValidationError, match='BNB-specific sampling requires --noise-mechanism bnb'):
        Configuration(
            command='train',
            noise_mechanism='gaussian',
            sampling_mode='b_min_sep',
        )


def test_bnb_configuration_requires_sampling_mode_b_min_sep() -> None:
    with pytest.raises(ValidationError, match='requires --sampling-mode b_min_sep or balls_in_bins'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='torch_sampler',
            bnb_b=2,
            bnb_p=0.1,
            bnb_bands=4,
        )


def test_balls_in_bins_requires_bnb_mechanism() -> None:
    with pytest.raises(ValidationError, match='BNB-specific sampling requires --noise-mechanism bnb'):
        Configuration(
            command='train',
            noise_mechanism='gaussian',
            sampling_mode='balls_in_bins',
        )


def test_bnb_configuration_balls_in_bins_does_not_require_p() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bnb',
        accountant='bnb',
        poisson_sampling=False,
        sampling_mode='balls_in_bins',
        bnb_b=10,
        bnb_bands=4,
    )
    assert cfg.sampling_mode == 'balls_in_bins'

def test_bnb_configuration_accepts_evr_calibration_options() -> None:
    cfg = Configuration(
        command='train',
        noise_mechanism='bnb',
        accountant='bnb',
        poisson_sampling=False,
        sampling_mode='b_min_sep',
        bnb_b=2,
        bnb_p=0.2,
        bnb_bands=1,
        bnb_num_samples=500,
        bnb_seed=7,
        bnb_confidence_alpha=1e-3,
        bnb_evr_num_checks=2,
        bnb_require_evr_pass=False,
        bnb_verify_both_directions=False,
        bnb_calibration_timeout_seconds=5.0,
    )
    assert cfg.bnb_num_samples == 500
    assert cfg.bnb_seed == 7
    assert cfg.bnb_confidence_alpha == 1e-3
    assert cfg.bnb_evr_num_checks == 2
    assert cfg.bnb_require_evr_pass is False
    assert cfg.bnb_verify_both_directions is False
    assert cfg.bnb_calibration_timeout_seconds == 5.0


def test_bnb_configuration_rejects_invalid_evr_calibration_options() -> None:
    with pytest.raises(ValidationError, match='--bnb-num-samples must be >= 1'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_b=2,
            bnb_p=0.2,
            bnb_bands=1,
            bnb_num_samples=0,
        )

    with pytest.raises(ValidationError, match='--bnb-confidence-alpha must be in \\(0, 1\\)'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_b=2,
            bnb_p=0.2,
            bnb_bands=1,
            bnb_confidence_alpha=1.0,
        )

    with pytest.raises(ValidationError, match='--bnb-calibration-timeout-seconds must be > 0'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_b=2,
            bnb_p=0.2,
            bnb_bands=1,
            bnb_calibration_timeout_seconds=0.0,
        )


def test_bnb_configuration_requires_all_b_min_sep_params() -> None:
    with pytest.raises(ValidationError, match='requires --bnb-b'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_p=0.1,
            bnb_bands=4,
        )

    with pytest.raises(ValidationError, match='requires --bnb-p'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_b=2,
            bnb_bands=4,
        )

    with pytest.raises(ValidationError, match='requires --bnb-bands'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_b=2,
            bnb_p=0.1,
        )


def test_bnb_configuration_rejects_invalid_param_ranges() -> None:
    with pytest.raises(ValidationError, match='--bnb-b must be >= 1'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_b=0,
            bnb_p=0.1,
            bnb_bands=4,
        )

    with pytest.raises(ValidationError, match='--bnb-p must be in \\(0, 1\\]'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_b=2,
            bnb_p=0.0,
            bnb_bands=4,
        )

    with pytest.raises(ValidationError, match='--bnb-bands must be >= 1'):
        Configuration(
            command='train',
            noise_mechanism='bnb',
            accountant='bnb',
            poisson_sampling=False,
            sampling_mode='b_min_sep',
            bnb_b=2,
            bnb_p=0.1,
            bnb_bands=0,
        )
