batch_size:
  max: 8096
  min: 64
  type: int
epochs:
  max: 1000
  min: 1
  type: int
learning_rate:
  max: 1.0
  min: 1.0e-06
  type: float
max_grad_norm:
  max: 1.0
  min: 1.0e-06
  type: float
model_name:
  options:
  - resnet18
  - resnet34
  - resnet50
  type: categorical
noise_multiplier:
  max: 1.0
  min: 1.0e-06
  type: float
