batch_size:
  max: 20480
  min: 8
  type: int
epochs:
  max: 20
  min: 1
  type: int
learning_rate:
  max: 1.0e-2
  min: 1.0e-07
  type: float
max_grad_norm:
  max: 10
  min: 0.2
  type: float
noise_multiplier:
  max: 1.0
  min: 1.0e-06
  type: float
model_name:
  options:
  - resnet18
  - resnet34
  - resnet50
  type: categorical
