batch_size:
  type: ordered
  min: 256
  # ordered categorical search!
  # options will be considered autoamtically:
  # 256, 512, 1024, ..., Full batch
learning_rate:
  min: 1e-4
  max: 0.05
  type: float
  log_space: True
max_grad_norm:
  type: ordered
  # ordered categorical search!
  options:
    - 1e-5
    - 1e-1
    - 1
    - 10
    - 25
    - 50
