batch_size:
  options:
  - 256
  - 512
  - 1024
  - 2048
  - 4096
  - -1
  type: categorical
learning_rate:
  max: 1.0e-1
  min: 1.0e-07
  type: float
  log_space: True
epochs:
  max: 200
  min: 1
  type: int
max_grad_norm:
  max: 10
  min: 0.2
  type: float
