batch_size:
  max: 250
  min: 10
  type: int
learning_rate:
  max: 4
  min: 1.0e-05
  type: float
  log_space: True
epochs:
  max: 200
  min: 1
  type: int
max_grad_norm:
  max: 10
  min: 0.2
  type: float
