train_metrics:
  - name: AUROC
    params:
      thresholds: 10
      average: macro

valid_metrics:
  - name: AUROC
    params:
      thresholds: 10
      average: macro

test_metrics:
  - name: AUROC
    params:
      thresholds: 10
      average: macro
