train_metrics:
  - name: AUROC
    alias: train_auroc
    params:
      thresholds: 10
      average: macro

valid_metrics:
  - name: AUROC
    alias: val_auroc
    params:
      thresholds: 10
      average: macro

test_metrics:
  - name: AUROC
    alias: test_auroc
    params:
      thresholds: 10
      average: macro