trials:
  - batch_size: 3301
    learning_rate: 0.238
    max_grad_norm: 5.424
  - batch_size: 3136
    learning_rate: 0.224
    max_grad_norm: 9.357
  - batch_size: 2557
    learning_rate: 0.075
    max_grad_norm: 31.610
  - batch_size: 4500
    learning_rate: 0.040
    max_grad_norm: 4.893
  - batch_size: 2218
    learning_rate: 0.880
    max_grad_norm: 14.122
