trials:
  - batch_size: 4500
    learning_rate: 0.028
    max_grad_norm: 0.673
  - batch_size: 4398
    learning_rate: 0.018
    max_grad_norm: 0.100
  - batch_size: 4500
    learning_rate: 0.026
    max_grad_norm: 4.321
  - batch_size: 4105
    learning_rate: 0.022
    max_grad_norm: 1.453
  - batch_size: 192
    learning_rate: 0.008
    max_grad_norm: 0.100
